name: echo_vibe
description: Voice recorder app with echo and export features
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.0.0
  path_provider: ^2.0.11
  flutter_sound: ^9.2.13
  ffmpeg_kit_flutter: ^4.5.1
  shared_preferences: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
